# Generated by Django 6.0.4 on 2026-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('jaundice', models.BooleanField()),
                ('abdominal_pain', models.BooleanField()),
                ('weight_loss', models.BooleanField()),
                ('fatigue', models.BooleanField()),
                ('fever', models.BooleanField()),
                ('bilirubin', models.FloatField()),
                ('alt', models.FloatField()),
                ('ast', models.FloatField()),
                ('alp', models.FloatField()),
                ('ca19_9', models.FloatField()),
                ('smoking', models.BooleanField()),
                ('alcohol', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('liver_disease_history', models.BooleanField()),
                ('gallstones', models.BooleanField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('probability', models.FloatField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
